# Generated by Django 6.0.5 on 2026-06-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeathteRecord',
            new_name='WeatherRecord',
        ),
    ]
