# Generated by Django 6.0.5 on 2026-06-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_weathterecord_weatherrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='temprature',
            new_name='temperature',
        ),
    ]
